library(shiny)

shinyUI(
  navbarPage("Groups",
             tabPanel("NYSE",
                      fluidRow(column(8,''),
                               column(4,textOutput('nyse_date'))),
                      
                      conditionalPanel("input.nysetabset == 'nyse_industry'",
                                       fluidRow(column(6,uiOutput("nyse_industry_menu")))),
                      conditionalPanel("input.nysetabset == 'nyse_super'",
                                       fluidRow(column(6,uiOutput("nyse_sup_indus")),
                                                column(6,uiOutput("nyse_sup_sup")))),
                      conditionalPanel("input.nysetabset == 'nyse_sector'",
                                       fluidRow(column(4,uiOutput("nyse_sec_indus")),
                                                column(4,uiOutput("nyse_sec_sup")),
                                                column(4,uiOutput("nyse_sec_sec")))),
                      conditionalPanel("input.nysetabset == 'nyse_subsector'",
                                       fluidRow(column(3,uiOutput("nyse_sub_indus")),
                                                column(3,uiOutput("nyse_sub_sup")),
                                                column(3,uiOutput("nyse_sub_sec")),
                                                column(3,uiOutput("nyse_sub_sub")))),
                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='nysetabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('industry'),
                                                                     value="nyse_industry",
                                                                     icon=icon("table")), 
                                                            tabPanel('SUPER',
                                                                     dataTableOutput('sup_sec'),
                                                                     value="nyse_super",
                                                                     icon=icon("table")), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('sec'),
                                                                     value="nyse_sector",
                                                                     icon=icon("table")),
                                                            tabPanel('SUBSECTOR',
                                                                     dataTableOutput('sub_sec'),
                                                                     value="nyse_subsector",
                                                                     icon=icon("table")),
                                                            tabPanel('HIGHS/LOWS', 
                                                                     fluidRow(column(12,plotOutput('nyse_new_highs'))),
                                                                     fluidRow(column(12,plotOutput('nyse_new_lows'))),
                                                                     fluidRow(column(12,plotOutput('nyse_index'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('INDEX', 
                                                                     fluidRow(column(12,plotOutput('nyse_index_solo'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('nyse_map'),
                                                                     icon=icon("list"))
                                      ),
                                                
                                                width=12))),
                      icon=icon("building-o")
),
             
             #####################################
             tabPanel("NASDAQ",
                      fluidRow(column(8,''),
                               column(4,textOutput('nasdaq_date'))),
                      conditionalPanel("input.nasdaqtabset == 'nasdaq_industry'",
                                       fluidRow(column(6,uiOutput("nasdaq_industry_menu")))),
                      conditionalPanel("input.nasdaqtabset == 'nasdaq_sector'",
                                       fluidRow(column(6,uiOutput("nasdaq_sec_indus")),
                                                column(6,uiOutput("nasdaq_sec_sec")))),                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='nasdaqtabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('nasdaq_industry'),
                                                                     value="nasdaq_industry",
                                                                     icon=icon("table")), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('nasdaq_sec'),
                                                                     value="nasdaq_sector",
                                                                     icon=icon("table")),
                                                            tabPanel('HIGHS/LOWS', 
                                                                     fluidRow(column(12,plotOutput('nasdaq_new_highs'))),
                                                                     fluidRow(column(12,plotOutput('nasdaq_new_lows'))),
                                                                     fluidRow(column(12,plotOutput('nasdaq_index'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('INDEX', 
                                                                     fluidRow(column(12,plotOutput('nasdaq_index_solo'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('nasdaq_map'),
                                                                     icon=icon("list"))
                                                            ),
                                                width=12))),
                      icon=icon("building-o")),
             
             #####################################
             tabPanel("ETPs",
                       fluidRow(column(8,''),
                                column(4,textOutput('etp_date'))),
                      conditionalPanel("input.etptabset == 'etp_normal'",
                                       fluidRow(column(6,uiOutput("etp_normal_menu")))),
                      conditionalPanel("input.etptabset == 'etp_inverse'",
                                       fluidRow(column(6,uiOutput("etp_inverse_menu")))),                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='etptabset',
                                                            tabPanel('NORMAL',
                                                                     dataTableOutput('etp_normal'),
                                                                     fluidRow(h3("PSMF Trend")),
                                                                     dataTableOutput('etp_normal_trend_psmf'),
                                                                     #fluidRow(h3("Short Term Trend")),
                                                                     #dataTableOutput('etp_normal_trend_short'),
                                                                     #fluidRow(h3('Intermediate Term Trend')),
                                                                     #dataTableOutput('etp_normal_trend_int'),
                                                                     #fluidRow(h3('Long Term Trend')),
                                                                     #dataTableOutput('etp_normal_trend_long'),
                                                                     value="etp_normal",
                                                                     icon=icon("table")), 
                                                            tabPanel('INVERSE',
                                                                     dataTableOutput('etp_inverse'),
                                                                     value="etp_inverse",
                                                                     icon=icon("table")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('etp_map'),
                                                                     icon=icon("list"))
                                                            ),
                                                width=12))),
                      icon=icon("exchange")),
             
             #####################################
             tabPanel("Special",
                       fluidRow(column(8,""),
                                column(4,textOutput('special_date'))),
                      conditionalPanel("input.specialtabset == 'special_industry'",
                                       fluidRow(column(6,uiOutput("special_industry_menu")))),
                      conditionalPanel("input.specialtabset == 'special_supersector'",
                                       fluidRow(column(6,uiOutput("special_sup_indus")),
                                                column(6,uiOutput("special_sup_sup")))),
                      conditionalPanel("input.specialtabset == 'special_sector'",
                                       fluidRow(column(4,uiOutput("special_sec_indus")),
                                                column(4,uiOutput("special_sec_sup")),
                                                column(4,uiOutput("special_sec_sec")))),
                      conditionalPanel("input.specialtabset == 'special_subsector'",
                                       fluidRow(column(3,uiOutput("special_sub_indus")),
                                                column(3,uiOutput("special_sub_sup")),
                                                column(3,uiOutput("special_sub_sec")),
                                                column(3,uiOutput("special_sub_sub")))),
                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='specialtabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('special_industry'),
                                                                     value="special_industry",
                                                                     icon=icon("table")), 
                                                            tabPanel('SUPERSECTOR',
                                                                     dataTableOutput('special_sup_sec'),
                                                                     value="special_supersector",
                                                                     icon=icon("table")), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('special_sec'),
                                                                     value="special_sector",
                                                                     icon=icon("table")), 
                                                            tabPanel('SUBSECTOR',
                                                                     dataTableOutput('special_subsec_table'),
                                                                     value="special_subsector",
                                                                     icon=icon("table")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('special_map'),
                                                                     icon=icon("list"))
                                                            ),
                                                width=12))),                      
                      icon=icon('flask')),
             
             ## setup
             tabPanel('Analysis',
                      fluidRow(column(8,textOutput('analysis_complete_time')),
                               column(4,textOutput('analysis_date'))),
                      fluidRow(column(12,h2('Insufficient History'))),
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='analysis_insufficient',
                                                            tabPanel('NYSE',
                                                                     dataTableOutput('insufficient_nyse'),
                                                                     icon=icon("flag")), 
                                                            tabPanel('NASDAQ',
                                                                     dataTableOutput('insufficient_nasdaq'),
                                                                     icon=icon("flag")),
                                                            tabPanel('ETP',
                                                                     dataTableOutput('insufficient_etp'),
                                                                     icon=icon("flag")),
                                                            tabPanel('Special',
                                                                     dataTableOutput('insufficient_special'),
                                                                     icon=icon("flag"))
                                      ),
                                      width=12))),
                      fluidRow(column(12,h2('Missing Prices'))),
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id="analysis_missing",
                                                            tabPanel('NYSE',
                                                                     dataTableOutput('missing_prices_nyse'),
                                                                     icon=icon("exclamation-triangle")),
                                                            tabPanel("NASDAQ",
                                                                     dataTableOutput('missing_prices_nasdaq'),
                                                                     icon=icon("exclamation-triangle"))
                                      ),
                                      width=12))),
                      fluidRow(column(12,h2('Stale Prices'))),
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id="analysis_stale",
                                                            tabPanel('NYSE',
                                                                     dataTableOutput('stale_prices_nyse'),
                                                                     icon=icon("adjust")),
                                                            tabPanel('NASDAQ',
                                                                     dataTableOutput('stale_prices_nasdaq'),
                                                                     icon=icon("adjust")),
                                                            tabPanel('ETP',
                                                                     dataTableOutput('stale_prices_etp'),
                                                                     icon=icon("adjust")),
                                                            tabPanel('Special',
                                                                     dataTableOutput('stale_prices_special'),
                                                                     icon=icon("adjust"))
                                                            )))),
                      icon=icon('gear')),
  tabPanel('Notes',
           htmlOutput('note_text'),
           icon=icon("paperclip")),
             
             #####################################
             header=NULL,
             footer=NULL,
             fluid=TRUE,
             inverse=TRUE,
             collapsable=FALSE,
             responsive=TRUE
             #theme="css/style.css",
             #navbarMenu("Modes",
            #            tabPanel("Snapshot",icon=icon("camera")),
            #            tabPanel("Trend",icon=icon("align-left")),
            #            tabPanel("Rotation",icon=icon("refresh"))
            # )
             
             
  )  # navbar page
)
