library(shiny)

shinyUI(
  navbarPage("Groups",
             tabPanel("NYSE",
                      conditionalPanel("input.nysetabset == 'INDUSTRY'",
                                       fluidRow(column(6,uiOutput("nyse_industry_menu")))),
                      conditionalPanel("input.nysetabset == 'SUPER'",
                                       fluidRow(column(6,uiOutput("nyse_sup_indus")),
                                                column(6,uiOutput("nyse_sup_sup")))),
                      conditionalPanel("input.nysetabset == 'SECTOR'",
                                       fluidRow(column(4,uiOutput("nyse_sec_indus")),
                                                column(4,uiOutput("nyse_sec_sup")),
                                                column(4,uiOutput("nyse_sec_sec")))),
                      conditionalPanel("input.nysetabset == 'SUBSECTOR'",
                                       fluidRow(column(3,uiOutput("nyse_sub_indus")),
                                                column(3,uiOutput("nyse_sub_sup")),
                                                column(3,uiOutput("nyse_sub_sec")),
                                                column(3,uiOutput("nyse_sub_sub")))),
                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='nysetabset',
                                                            tabPanel('INDUSTRY',dataTableOutput('industry')), 
                                                            tabPanel('SUPER',dataTableOutput('sup_sec')), 
                                                            tabPanel('SECTOR',dataTableOutput('sec')),
                                                            tabPanel('SUBSECTOR',dataTableOutput('sub_sec'))),
                                                width=12))),
                      icon=icon("table")),
             
             #####################################
             tabPanel("NASDAQ",
                      conditionalPanel("input.nasdaqtabset == 'INDUSTRY'",
                                       fluidRow(column(6,uiOutput("nasdaq_industry_menu")))),
                      conditionalPanel("input.nasdaqtabset == 'SECTOR'",
                                       fluidRow(column(6,uiOutput("nasdaq_sec_indus")),
                                                column(6,uiOutput("nasdaq_sec_sec")))),                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='nasdaqtabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('nasdaq_industry')), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('nasdaq_sec'))),
                                                width=12))),
                      icon=icon("table")),
             
             #####################################
             tabPanel("ETPs",
                      conditionalPanel("input.etptabset == 'NORMAL'",
                                       fluidRow(column(6,uiOutput("etp_normal_menu")))),
                      conditionalPanel("input.etptabset == 'INVERSE'",
                                       fluidRow(column(6,uiOutput("etp_inverse_menu")))),                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='etptabset',
                                                            tabPanel('NORMAL',
                                                                     dataTableOutput('etp_normal')), 
                                                            tabPanel('INVERSE',
                                                                     dataTableOutput('etp_inverse'))),
                                                width=12))),
                      icon=icon("table")),
             
             #####################################
             tabPanel("Special",
                      
                      conditionalPanel("input.specialtabset == 'INDUSTRY'",
                                       fluidRow(column(6,uiOutput("special_industry_menu")))),
                      conditionalPanel("input.specialtabset == 'SUPERSECTOR'",
                                       fluidRow(column(6,uiOutput("special_sup_indus")),
                                                column(6,uiOutput("special_sup_sup")))),
                      conditionalPanel("input.specialtabset == 'SECTOR'",
                                       fluidRow(column(4,uiOutput("special_sec_indus")),
                                                column(4,uiOutput("special_sec_sup")),
                                                column(4,uiOutput("special_sec_sec")))),
                      conditionalPanel("input.specialtabset == 'SUBSECTOR'",
                                       fluidRow(column(3,uiOutput("special_sub_indus")),
                                                column(3,uiOutput("special_sub_sup")),
                                                column(3,uiOutput("special_sub_sec")),
                                                column(3,uiOutput("special_sub_sub")))),
                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='specialtabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('special_industry')), 
                                                            tabPanel('SUPERSECTOR',
                                                                     dataTableOutput('special_sup_sec')), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('special_sec')), 
                                                            tabPanel('SUBSECTOR',
                                                                     dataTableOutput('special_subsec_table'))),
                                                width=12))),                      
                      icon=icon('table')),
             
             #####################################
             header=NULL,
             footer=NULL,
             fluid=TRUE,
             inverse=TRUE,
             collapsable=FALSE,
             responsive=TRUE,
             #theme="css/style.css",
             navbarMenu("Modes",
                        tabPanel("Snapshot",icon=icon("camera")),
                        tabPanel("Trend",icon=icon("align-left")),
                        tabPanel("Rotation",icon=icon("refresh")),
                        tabPanel("Plots",icon=icon("bar-chart-o"))
             )
             
             
  )  # navbar page
)
