library(shiny)

shinyUI(
  navbarPage("Groups",
             tabPanel("NYSE",
                      conditionalPanel("input.nysetabset == 'INDUSTRY'",
                                       fluidRow(column(6,uiOutput("nyse_industry_menu")))),
                      conditionalPanel("input.nysetabset == 'SUPER'",
                                       fluidRow(column(6,uiOutput("nyse_sup_indus")),
                                                column(6,uiOutput("nyse_sup_sup")))),
                      conditionalPanel("input.nysetabset == 'SECTOR'",
                                       fluidRow(column(4,uiOutput("nyse_sec_indus")),
                                                column(4,uiOutput("nyse_sec_sup")),
                                                column(4,uiOutput("nyse_sec_sec")))),
                      conditionalPanel("input.nysetabset == 'SUBSECTOR'",
                                       fluidRow(column(3,uiOutput("nyse_sub_indus")),
                                                column(3,uiOutput("nyse_sub_sup")),
                                                column(3,uiOutput("nyse_sub_sec")),
                                                column(3,uiOutput("nyse_sub_sub")))),
                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='nysetabset',
                                                            tabPanel('INDUSTRY',dataTableOutput('industry'),
                                                                     icon=icon("table")), 
                                                            tabPanel('SUPER',dataTableOutput('sup_sec'),
                                                                     icon=icon("table")), 
                                                            tabPanel('SECTOR',dataTableOutput('sec'),
                                                                     icon=icon("table")),
                                                            tabPanel('SUBSECTOR',dataTableOutput('sub_sec'),
                                                                     icon=icon("table")),
                                                            tabPanel('HIGHS/LOWS', 
                                                                     fluidRow(column(12,plotOutput('nyse_new_highs'))),
                                                                     fluidRow(column(12,plotOutput('nyse_new_lows'))),
                                                                     fluidRow(column(12,plotOutput('nyse_index'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('INDEX', 
                                                                     fluidRow(column(12,plotOutput('nyse_index_solo'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('nyse_map'),
                                                                     icon=icon("list"))
                                      ),
                                                
                                                width=12))),
                      icon=icon("building-o")),
             
             #####################################
             tabPanel("NASDAQ",
                      conditionalPanel("input.nasdaqtabset == 'INDUSTRY'",
                                       fluidRow(column(6,uiOutput("nasdaq_industry_menu")))),
                      conditionalPanel("input.nasdaqtabset == 'SECTOR'",
                                       fluidRow(column(6,uiOutput("nasdaq_sec_indus")),
                                                column(6,uiOutput("nasdaq_sec_sec")))),                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='nasdaqtabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('nasdaq_industry'),
                                                                     icon=icon("table")), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('nasdaq_sec'),
                                                                     icon=icon("table")),
                                                            tabPanel('HIGHS/LOWS', 
                                                                     fluidRow(column(12,plotOutput('nasdaq_new_highs'))),
                                                                     fluidRow(column(12,plotOutput('nasdaq_new_lows'))),
                                                                     fluidRow(column(12,plotOutput('nasdaq_index'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('INDEX', 
                                                                     fluidRow(column(12,plotOutput('nasdaq_index_solo'))),
                                                                     icon=icon("bar-chart-o")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('nasdaq_map'),
                                                                     icon=icon("list"))
                                                            ),
                                                width=12))),
                      icon=icon("building-o")),
             
             #####################################
             tabPanel("ETPs",
                      conditionalPanel("input.etptabset == 'NORMAL'",
                                       fluidRow(column(6,uiOutput("etp_normal_menu")))),
                      conditionalPanel("input.etptabset == 'INVERSE'",
                                       fluidRow(column(6,uiOutput("etp_inverse_menu")))),                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='etptabset',
                                                            tabPanel('NORMAL',
                                                                     dataTableOutput('etp_normal'),
                                                                     icon=icon("table")), 
                                                            tabPanel('INVERSE',
                                                                     dataTableOutput('etp_inverse'),
                                                                     icon=icon("table")),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('etp_map'),
                                                                     icon=icon("list"))
                                                            ),
                                                width=12))),
                      icon=icon("exchange")),
             
             #####################################
             tabPanel("Special",
                      
                      conditionalPanel("input.specialtabset == 'INDUSTRY'",
                                       fluidRow(column(6,uiOutput("special_industry_menu")))),
                      conditionalPanel("input.specialtabset == 'SUPERSECTOR'",
                                       fluidRow(column(6,uiOutput("special_sup_indus")),
                                                column(6,uiOutput("special_sup_sup")))),
                      conditionalPanel("input.specialtabset == 'SECTOR'",
                                       fluidRow(column(4,uiOutput("special_sec_indus")),
                                                column(4,uiOutput("special_sec_sup")),
                                                column(4,uiOutput("special_sec_sec")))),
                      conditionalPanel("input.specialtabset == 'SUBSECTOR'",
                                       fluidRow(column(3,uiOutput("special_sub_indus")),
                                                column(3,uiOutput("special_sub_sup")),
                                                column(3,uiOutput("special_sub_sec")),
                                                column(3,uiOutput("special_sub_sub")))),
                      
                      fluidRow(column(12,
                                      mainPanel(tabsetPanel(id='specialtabset',
                                                            tabPanel('INDUSTRY',
                                                                     dataTableOutput('special_industry'),
                                                                     icon=icon("table")), 
                                                            tabPanel('SUPERSECTOR',
                                                                     dataTableOutput('special_sup_sec'),
                                                                     icon=icon("table")), 
                                                            tabPanel('SECTOR',
                                                                     dataTableOutput('special_sec'),
                                                                     icon=icon("table")), 
                                                            tabPanel('SUBSECTOR',
                                                                     dataTableOutput('special_subsec_table')),
                                                            tabPanel('MAP',
                                                                     dataTableOutput('special_map'),
                                                                     icon=icon("list"))
                                                            ),
                                                width=12))),                      
                      icon=icon('flask')),
             
             #####################################
             header=NULL,
             footer=NULL,
             fluid=TRUE,
             inverse=TRUE,
             collapsable=FALSE,
             responsive=TRUE,
             #theme="css/style.css",
             navbarMenu("Modes",
                        tabPanel("Snapshot",icon=icon("camera")),
                        tabPanel("Trend",icon=icon("align-left")),
                        tabPanel("Rotation",icon=icon("refresh"))
                        # tabPanel("Plots",icon=icon("bar-chart-o"))
             )
             
             
  )  # navbar page
)
